### ISSUE TITLE
Update VisualVM instructions to visualvm 2.x

### ISSUE THREAD

**Issue by AnEmortalKid** [cchesser/java-perf-workshop#12]
* We should update the screenshots and instructions using VisualVM 1.4 and require that to be downloaded as well.

**Comment by AnEmortalKid** [comment]
VisualVM 2.x has an R Console, perhaps we can do something neat with it.

**Comment by cchesser** [comment]
@AnEmortalKid, the site has now transitioned to GitHub pages. You can now start adding content in the docs folder. Changes, once merged to `main` get auto-published with GitHub actions.

Site currently hosted here: https://jvmperf.net/

**Comment by AnEmortalKid** [comment]
Screenshots updated in #39 . I'll separate an issue to play with the R Console and see if there's anything I can do on it !
