### ISSUE TITLE
Update the documentation flow of tooling references for memory analysis

### ISSUE THREAD

**Issue by cchesser** [cchesser/java-perf-workshop#26]
Consider making updates to the flow of the workshop:

- [x] JOverflow first: Simple and guides them to problematic areas
- [x] Eclipse MAT OQL starter to get familar how to ask specific questions about a heap dump
- [x] Eclipse MAT plugin for expert-mode ([mat-calcite-plugin](https://github.com/vlsi/mat-calcite-plugin): More extensive type SQL-like statements
- [x] VisualVM
- [x] Workshop for them to find the problem (memory leak)

**Comment by AnEmortalKid** [comment]
All subitems completed!
